### ISSUE TITLE
[gulp] Unnesessary Dependency with `gulp-ruby-sass`

### ISSUE THREAD

**Issue by omero** [hechoendrupal/drupalgenerator#6]
When setup the dev environment locally i get the next error running `gulp watch` command:

```
[14:42:04] Starting 'sync group3:0'...
[14:42:04] Starting 'sync group0:0'...
[14:42:04] Starting 'clean'...
[14:42:04] Finished 'clean' after 18 ms
[14:42:04] Finished 'sync group0:0' after 20 ms
[14:42:04] Starting 'sync group0:1'...
[14:42:04] Starting 'html'...
[14:42:04] Starting 'styles'...
[14:42:05] Starting 'scripts'...
[14:42:05] Starting 'images'...
[14:42:05] Starting 'fonts'...
[14:42:05] Starting 'extras'...
[14:42:05] Sass Error { [Error: Gem sass is not installed.]
  message: 'Gem sass is not installed.',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-ruby-sass',
  __safety: { toString: [Function] } }
[14:42:05] Finished 'fonts' after 26 ms
```

And the styles just broke.
![screen shot 2015-10-18 at 3 20 41 pm](https://github-cloud.s3.amazonaws.com/assets/1909779/10566401/e4b7ed40-75ab-11e5-9d94-67791f3dbde9.png)

This is because gulp looks for sass ruby gem, maybe this is not necessary because we have `gulp-sass` plugin that depends from `node-sass`, to this point the most of the styles are provided from `material-ui` and we don't need any dependency of ruby, with the `gulp-sass` plugin it's enough to work on this project.

**Comment by omero** [comment]
any thoughts about this @antillas21 ?

**Comment by antillas21** [comment]
I just commented @jmolivas that I had no way to realize any of this as my local env always includes `ruby` and the corresponding `sass` gem, :smile: 

But after checking https://github.com/hechoendrupal/drupalgenerator/pull/7 I can see this dependency can be avoided and keep the project dependencies contained within the `package.json` file, this is, no need to have `ruby` and the `sass` gem installed... that is always a win.

So I say, :shipit:

**Comment by omero** [comment]
Cool @antillas21 so let's ~~kill all ruby things~~ merge #7 ;) 

Thanks!

**Comment by jmolivas** [comment]
Closing his since related PR https://github.com/hechoendrupal/drupalgenerator/pull/7 was merged
